### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by mahdi943** [jackcook/bigger-fish#1]
Hello,

I got this error while I try to run: 
python record_data.py --browser chrome --num_runs 1 --sites_list google.com --trace_length 5

![image](https://user-images.githubusercontent.com/48979569/187069905-3441a2fb-8471-4fda-b929-f5ae45445fbb.png)

Could you please help me with that?

Mahdi

**Comment by jackcook** [comment]
This is a Windows-specific issue -- try replacing line 202 in `record_data.py` with `procs = []` and running it again. Please let me know if everything runs correctly with that change -- if so, I can merge in a change that makes the fix a bit more permanent.

**Comment by mahdi943** [comment]
> This is a Windows-specific issue -- try replacing line 202 in `record_data.py` with `procs = []` and running it again. Please let me know if everything runs correctly with that change -- if so, I can merge in a change that makes the fix a bit more permanent.

I got a new error :
![image](https://user-images.githubusercontent.com/48979569/187550898-e7f92f3e-a2d1-490d-b987-c0cd1579ea7c.png)

**Comment by jackcook** [comment]
Try replacing line 191 with:

if opts.disable_chrome_sandbox:

**Comment by mahdi943** [comment]
> Try replacing line 191 with:
> 
> if opts.disable_chrome_sandbox:

It works! that opened google twice. thanks. 
how can I download the traces? (I opened "index.html" under the attacker directory but collect trace doesn't work )

![image](https://user-images.githubusercontent.com/48979569/187555097-bb29d140-7969-414a-91d0-9c9ab411fbef.png)

**Comment by jackcook** [comment]
They should be getting saved to a folder called “data” in the directory you were in when you ran the command. You can change the name of the output folder with the --out_directory <name> argument, and you can see an example about how to read traces from an output folder in this script: https://github.com/jackcook/bigger-fish/blob/main/scripts/check_results.py

**Comment by mahdi943** [comment]
Unfortunately,  folder 'data' is empty after running the command.

**Comment by jackcook** [comment]
Are you sure? In the screenshot you showed me, it looks like you got a warning that data already existed in the "data" directory, and you chose to overwrite it. It looks like it should be in `D:\big-fisher\bigger-fish-main\data`. What if you try using another directory name with the `--out_directory <name>` argument?

**Comment by mahdi943** [comment]
data folder is empty after running, I tried on linux and it works fine.
thanks.

**Comment by mahdi943** [comment]
BTW, can I have "counter" graphical measurements as an image (jpg) for some other part of a website?
e.g. instead of "amazon com"  can I say "amazon.com/seller" in input argument

**Comment by jackcook** [comment]
Could you try debugging it on Windows to see why data isn't getting saved? It should be saving data to the output file on line 479 of record_data.py.

Right now, a non-root URL as `amazon.com/seller` isn't supported -- a couple things would need to be fixed, such as the filenames on lines 430 and 450 of record_data.py. I'd welcome a PR that resolves those issues.

And if you're able to save and load the traces on Linux, you can generate images similar to the ones we have in the paper with something like this: https://stackoverflow.com/questions/45841786/creating-a-1d-heat-map-from-a-line-graph

**Comment by mahdi943** [comment]
I ran code successfully on windows. It saved a pkl file in "data" folder.  You may add some libs such as "flask", and "requests" in requirements.txt. All those lib versions work with Python 3.9.  e.g. numpy==1.21.0 isn't supported by python 3.10.

**Comment by jackcook** [comment]
Ah, I didn't realize flask wasn't in the requirements file. I'll add it and update some of the others, thanks for pointing that out. I'll close this for now, but please let me know if you run into any other issues.
