### ISSUE TITLE
Heatmap images from traces

### ISSUE THREAD

**Issue by mahdi943** [jackcook/bigger-fish#2]
Hi,
Could you please provide me with a heatmap generator from pkl files?

Thank,
Mahdi

**Comment by jackcook** [comment]
Hi Mahdi, as I mentioned in your last issue, please consult examples available for loading the traces from the pickle file (see get_data in scripts/check_results.py) and examples for visualizing this data with matplotlib, such as https://stackoverflow.com/questions/45841786/creating-a-1d-heat-map-from-a-line-graph. Please let me know if you run into any issues.
