### ISSUE TITLE
record_data.py

### ISSUE THREAD

**Issue by zongtaili** [jackcook/bigger-fish#7]
hello，i ran python code `record_data.py` with your documentation in windows environment，after executing the example command 

> python record_data.py --browser chrome --num_runs 1 --sites_list google.com --trace_length 5

i got error "subprocess.CalledProcessError: Command '['ps', 'aux']' returned non-zero exit status 1" at line 202

have you ever encountered such a situation？how could i deal with this?

**Comment by jackcook** [comment]
I can’t push a fix right now, but in the meantime you can check out issue #1 for a solution. Please let me know if you run into any other issues.

**Comment by zongtaili** [comment]
thank you very much! 
i have solved the problem based on issue #1, the changes that i made is at line 202 and line 191 just as you said. thanks your reply!
                                                                                     li zongtai
